name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Checkout du code
      - name: Checkout code
        uses: actions/checkout@v3

      # Étape 2 : Configurer Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Étape 3 : Construire et pousser les images Docker
      - name: Build and push Backend Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./server
          push: true
          tags: hamidnazari77/server:latest

      - name: Build and push Frontend Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./client
          push: true
          tags: hamidnazari77/client:latest

      # Étape 4 : Déployer sur Render
      - name: Deploy to Render
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        run: |
          curl -X POST "$RENDER_API_KEY"
